### ISSUE TITLE
RS485 interface sometimes seems to get stuck transmitting back to EGSE

### ISSUE THREAD

**Issue by StefanoSperetta** [DelfiSpace/HPI_FlightSoftware#1]
Check interface, verify also that a termination resistor improves the system

**Comment by MFvandenBos** [comment]
@StefanoSperetta Can you explain what this problem looks like? I have not run into situations where the microcontroller gets stuck. I did have sometimes that the website gets stuck

**Comment by StefanoSperetta** [comment]
This issue might be solved by a previous commit (basically the interrupt on the EGSE was sometimes disabled). I think this is solved and it can be closed.

Did you still notice communication issues via the HPI (packet loss, etc...)?

**Comment by MFvandenBos** [comment]
There is sometimes a communication issue: 
I ran a number of tests, many times in 1 testsuite. 

It always fails, but sometimes there is also a failure due to a communication glitch. 
The lines that end with 19 do not have communication glitch. 
![image](https://user-images.githubusercontent.com/35063713/72621724-1a4b7900-3942-11ea-8c83-b235fd9afc6a.png)

**Comment by StefanoSperetta** [comment]
I do not have an HPI with me but I check the latest HPI sw (with Casper's changes) and make sure you can program it on Monday to test. I will also try to debug the communication bus a little more...

**Comment by StefanoSperetta** [comment]
Problem solved by disabling low-power mode in TaskManager (https://github.com/DelfiSpace/DelfiPQcore/commit/180a36b59afd7e7b77c749fabf182d2c6f1acc56)
